# Generated by Django 5.1.4 on 2025-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_created_at_todo_deadline_todo_last_active_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='stopped', max_length=20),
        ),
    ]
