# Generated by Django 5.1.4 on 2025-01-22 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_member_todo_created_at_todo_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.team'),
        ),
    ]
