# Generated by Django 5.1.4 on 2025-01-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_elapsed_time_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='elapsed_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='not_started', max_length=20),
        ),
    ]
