# Generated by Django 5.1.4 on 2025-02-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_category_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
