# Generated by Django 5.1.4 on 2025-02-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_team_members_remove_teammember_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
