# Generated by Django 5.1.4 on 2025-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='elapsed_time',
            field=models.FloatField(default=0),
        ),
    ]
