# Generated by Django 5.1.4 on 2025-01-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_team_name 2'),
        ('todos', '0004_alter_team_name'),
    ]

    operations = [
    ]
