# Generated by Django 5.1.4 on 2025-01-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='elapsed_time',
            field=models.DurationField(default='0'),
        ),
    ]
